In [22]:
import torch

## torch.view()

### Note on `torch.view()`

`torch.view()` is a method in PyTorch that reshapes a tensor without changing its data. It returns a new tensor with the same data but a different shape, as specified by the arguments passed to `view()`.

#### Key Points:
- The new shape must be compatible with the original shape. For example, the total number of elements must remain the same.
- Use `-1` as a placeholder for one dimension, and PyTorch will infer its size based on the other dimensions.

#### Example:
```python
import torch
x = torch.arange(12)  # A tensor with 12 elements
x_reshaped = x.view(3, 4)  # Reshape to 3 rows and 4 columns
print(x_reshaped)
```

This will output a 3x4 tensor reshaped from the original 1D tensor.

In [23]:
x = torch.arange(12)  # A tensor with 12 elements
x_reshaped = x.view(3, 4)  # Reshape to 3 rows and 4 columns
print(x)
print(x_reshaped)

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])
tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])


### Difference between `view()` and `reshape()`

Both `view()` and `reshape()` are used to change the shape of a tensor in PyTorch, but they have some differences in behavior:

#### `view()`:
- **Memory Contiguity**: Requires the tensor to be contiguous in memory. If the tensor is not contiguous, you need to call `.contiguous()` before using `view()`.
- **Efficiency**: Does not create a copy of the data; instead, it returns a new tensor that shares the same data as the original tensor.
- **Use Case**: Preferred when you are sure the tensor is contiguous and want to avoid unnecessary data copies.

#### `reshape()`:
- **Flexibility**: Can handle non-contiguous tensors by internally making them contiguous if needed.
- **Memory**: May return a view of the original tensor or create a copy, depending on whether the new shape is compatible with the original memory layout.
- **Use Case**: Preferred when you are unsure about the memory contiguity of the tensor.



In [24]:

import torch
x = torch.arange(12)  # A tensor with 12 elements

# Using view()
x_view = x.view(3, 4)  # Reshape to 3 rows and 4 columns
print("Using view:")
print(x_view)

# Using reshape()
x_reshape = x.reshape(3, -1)  # Reshape to 3 rows and 4 columns
print("Using reshape:")
print(x_reshape)

x[0] = 99
print(x)
print(x_view)
print(x_reshape)

Using view:
tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])
Using reshape:
tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])
tensor([99,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])
tensor([[99,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])
tensor([[99,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])


In [25]:

x = torch.randn(4, 3)
x_t = x.t()        # transpose
try:    
    x_t.view(12)       # ❌ RuntimeError
except RuntimeError as e:
    print(f"RuntimeError: {e}") # Transposed tensors are not contiguous in memory, so view() cannot be used directly.
x_t.contiguous().view(12)

RuntimeError: view size is not compatible with input tensor's size and stride (at least one dimension spans across two contiguous subspaces). Use .reshape(...) instead.


tensor([ 0.7681, -1.2338, -1.5117,  0.0714, -1.9503,  1.2341, -0.2769, -1.0951,
         0.0803, -1.4415,  1.1587,  0.3525])

In [26]:
A = torch.randint(0,100,(3,4))
print(A)

tensor([[31, 96, 43, 68],
        [46,  8, 49, 81],
        [97, 66, 92, 55]])


In [27]:

print("Shape of A.view(1,3,4):", A.view(1,3,4).shape, '\n', A.view(1,3,4))


Shape of A.view(1,3,4): torch.Size([1, 3, 4]) 
 tensor([[[31, 96, 43, 68],
         [46,  8, 49, 81],
         [97, 66, 92, 55]]])


#### View as 3-D(broadcast)

In [28]:
try:
    print("Shape of A.view(3,3,4):", A.view(3,3,4).shape, '\n', A.view(3,3,4))
except RuntimeError as e:
    print("Error:", e)  

Error: shape '[3, 3, 4]' is invalid for input of size 12


In [29]:
# broadcasting for 1D and 2D tensors where 1 dim is 1
B = torch.tensor([1,2,3])
print("Shape of B:", B.shape)
print("Shape of B.view(1,3):", B.view(1,3).shape, '\n', B.view(1,3))
print("Shape of B.view(3,1):", B.view(3,1).shape, '\n', B.view(3,1))
# broadcast B to shape (4,3)
# we need to use expand instead of view to broadcast B to shape (4,3) because view only changes the shape without changing the data, while expand creates a new view of the data with the desired shape. 
# If we try to use view to change the shape of B to (4,3), it will raise an error because the total number of elements in B (3) does not match the total number of elements in the new shape (12).
print("Shape of B.view(1,3) broadcasted to (4,3):", B.view(1,3).expand(4,3).shape, '\n', B.view(1,3).expand(4,3))
# broadcast B to shape (3,4)
print("Shape of B.view(3,1) broadcasted to (3,4):", B.view(3,1).expand(3,4).shape, '\n', B.view(3,1).expand(3,4))

Shape of B: torch.Size([3])
Shape of B.view(1,3): torch.Size([1, 3]) 
 tensor([[1, 2, 3]])
Shape of B.view(3,1): torch.Size([3, 1]) 
 tensor([[1],
        [2],
        [3]])
Shape of B.view(1,3) broadcasted to (4,3): torch.Size([4, 3]) 
 tensor([[1, 2, 3],
        [1, 2, 3],
        [1, 2, 3],
        [1, 2, 3]])
Shape of B.view(3,1) broadcasted to (3,4): torch.Size([3, 4]) 
 tensor([[1, 1, 1, 1],
        [2, 2, 2, 2],
        [3, 3, 3, 3]])


# `torch.squeeze()` and `torch.unsqueeze()`

## `torch.squeeze()`

### Purpose
Removes dimensions of size **1**.

In [37]:
# Basic squeeze — removes all size-1 dims
x = torch.randn(4, 1, 3, 1)
print("x: ", x.shape)    # torch.Size([4, 1, 3, 1])
y = x.squeeze()
print("y: ", y.shape)    # torch.Size([4, 3])

# Squeeze a specific dimension
x2 = torch.randn(4, 1, 3)
y2 = x2.squeeze(1)
print(y2.shape)   # torch.Size([4, 3])

# If the dim is not size 1, nothing happens
x3 = torch.randn(4, 2, 3)
y3 = x3.squeeze(1)
print(y3.shape)   # torch.Size([4, 2, 3])

x:  torch.Size([4, 1, 3, 1])
y:  torch.Size([4, 3])
torch.Size([4, 3])
torch.Size([4, 2, 3])


## `torch.unsqueeze()`

### Purpose
Adds a dimension of size **1** at a specified index.

In [31]:
x = torch.randn(4, 3)
print(x.shape)               # torch.Size([4, 3])

# Add dim at index 0
y = x.unsqueeze(0)
print(y.shape)               # torch.Size([1, 4, 3])

# Add at other positions
print(x.unsqueeze(1).shape)  # torch.Size([4, 1, 3])
print(x.unsqueeze(2).shape)  # torch.Size([4, 3, 1])

torch.Size([4, 3])
torch.Size([1, 4, 3])
torch.Size([4, 1, 3])
torch.Size([4, 3, 1])


## Relationship to Shape and Indexing

If `x.shape == (4, 3)`:

| Operation        | Result Shape |
| ---------------- | ------------ |
| `x.unsqueeze(0)` | (1, 4, 3)    |
| `x.unsqueeze(1)` | (4, 1, 3)    |
| `x.unsqueeze(2)` | (4, 3, 1)    |

Dimension index refers to the position in the shape tuple.

---

## Why This Matters (Very Important in DL)

### (a) Batch Dimension

Neural networks expect input like `(batch, channels, height, width)`. If you have a single image, add a batch dimension:

In [32]:
img = torch.randn(3, 256, 256)
print(img.shape)         # torch.Size([3, 256, 256])

img = img.unsqueeze(0)   # add batch dimension
print(img.shape)         # torch.Size([1, 3, 256, 256])

torch.Size([3, 256, 256])
torch.Size([1, 3, 256, 256])


### (b) Broadcasting

`x + bias` works when shapes are compatible. If `bias` is incompatible, use `unsqueeze` to align dimensions:

In [33]:
x = torch.randn(4, 3)
bias = torch.randn(3)
print((x + bias).shape)   # works: bias broadcasts across rows — torch.Size([4, 3])

# If bias shape is incompatible, use unsqueeze
bias2 = torch.randn(4)
bias2 = bias2.unsqueeze(1)  # shape: (4, 1) — broadcasts across columns
print(bias2.shape)          # torch.Size([4, 1])
print((x + bias2).shape)    # torch.Size([4, 3])

torch.Size([4, 3])
torch.Size([4, 1])
torch.Size([4, 3])


## Equivalent Alternatives

You can also use `None` indexing instead of `unsqueeze`:

In [34]:
x = torch.randn(4, 3)
print(x[None, :, :].shape)   # same as unsqueeze(0) → torch.Size([1, 4, 3])
print(x[:, None, :].shape)   # same as unsqueeze(1) → torch.Size([4, 1, 3])

torch.Size([1, 4, 3])
torch.Size([4, 1, 3])


## Memory Behavior

* `squeeze()` and `unsqueeze()` do **not copy data**
* They only change tensor metadata (view operation)
* Very cheap operations

---

## Common Mistakes

### Mistake 1: Accidentally removing the batch dimension

In [36]:
x = torch.randn(1, 3, 256, 256)

# ❌ Bad: squeeze() removes ALL size-1 dims, including batch
x_bad = x.squeeze()
print(x_bad.shape)   # torch.Size([3, 256, 256]) — batch dim gone!

# ✅ Better: always specify which dim to squeeze
x_good = x.squeeze(0)
print(x_good.shape)  # torch.Size([3, 256, 256]) — intentional

torch.Size([3, 256, 256])
torch.Size([3, 256, 256])


### Mistake 2: Confusing `unsqueeze` with `reshape`

`unsqueeze()` only inserts a size-1 dimension — it does **not** rearrange elements.

---

## Mental Model

* `unsqueeze(dim)` → insert axis at position `dim`
* `squeeze(dim)` → remove axis at `dim` if size == 1
* Pure shape manipulation, no data movement

## Verifying Memory Behavior with Storage Pointers

Two tensors share the same underlying data if and only if `untyped_storage().data_ptr()` returns the **same address**.

### `unsqueeze()` — Always a View

In [39]:
x = torch.randn(2, 3)
y = x.unsqueeze(0)

print(x.untyped_storage().data_ptr())
print(y.untyped_storage().data_ptr())

4972836480
4972836480


### `clone()` — Always Copies Data

In [40]:
z = x.clone()
print(z.storage().data_ptr())

4972837504


### `view()` — View on Contiguous Tensor (Same Storage)

In [41]:
x = torch.randn(2, 3)
y = x.view(6)
print(x.untyped_storage().data_ptr())
print(y.untyped_storage().data_ptr())

4395801344
4395801344


### `view()` — Fails on Non-Contiguous Tensor

In [43]:
x = torch.randn(2, 3)
x_t = x.t()  # transpose → non-contiguous
try:
    x_t.view(6)  # RuntimeError: view() can only be called on contiguous tensors. Use .contiguous() to get a contiguous copy of the tensor and then call view() on that.
except RuntimeError as e:
    print(f"RuntimeError: {e}")

RuntimeError: view size is not compatible with input tensor's size and stride (at least one dimension spans across two contiguous subspaces). Use .reshape(...) instead.


### `reshape()` — View When Tensor is Contiguous (Same Storage)

In [44]:
x = torch.randn(2, 3)
y = x.reshape(6)
print(x.untyped_storage().data_ptr())
print(y.untyped_storage().data_ptr())

4744245056
4744245056


### `reshape()` — Copies When Tensor is Non-Contiguous (Different Storage)

In [46]:
x = torch.randn(2, 3)
x_t = x.t()   # non-contiguous
print(x_t.is_contiguous())  # False
y = x_t.reshape(6)
print(x.untyped_storage().data_ptr())
print(y.untyped_storage().data_ptr())

False
4972841920
4314951552


### Performance Comparison
| Operation   | Copies Data? | Can Fail? |
| ----------- | ------------ | --------- |
| `view()`    | Never        | Yes       |
| `reshape()` | Sometimes    | No        |




### Clean Mental Model

`view()`:

> "I refuse to copy. If layout doesn’t match, I crash."

`reshape()`:

> "I will try not to copy. But if necessary, I will."

---

### When Should You Use Which?

In research code (like yours):

* Use `reshape()` for safety
* Use `view()` when you are certain tensor is contiguous and want stricter control

---



Think of it as “lookup by label”.

If:



In [ ]:
counts = np.bincount(y_imb.astype(int))



and `y_imb = [0, 1, 1, 1]`, then:



In [ ]:
counts = [1, 3]
# index:   0  1



Now the second indexing:



In [ ]:
counts[y_imb.astype(int)]



means:
- for first sample label `0` -> `counts[0] = 1`
- for second sample label `1` -> `counts[1] = 3`
- for third sample label `1` -> `counts[1] = 3`
- for fourth sample label `1` -> `counts[1] = 3`

So output is:



In [ ]:
[1, 3, 3, 3]



In general, NumPy “fancy indexing” with an integer array does element-wise index lookup.  
So if `idx = [2,0,2]`, then `arr[idx] = [arr[2], arr[0], arr[2]]`.